# Pre-Processing

In [1]:
import cv2

Resize

In [2]:
img = cv2.imread('/content/example-image.jpg', cv2.IMREAD_UNCHANGED)

width = 100
height = 100
dim = (width, height)

resized = cv2.resize(img, dim, interpolation= cv2.INTER_AREA)

# Normalization

## Max Value

In [4]:
img = cv2.imread('/content/example-image.jpg', cv2.IMREAD_UNCHANGED)

# By Max value
img = img/255.0

In [5]:
print(img)

[[[0.14509804 0.18823529 0.3372549 ]
  [0.14117647 0.18431373 0.33333333]
  [0.1372549  0.18039216 0.32941176]
  ...
  [0.13333333 0.11372549 0.11764706]
  [0.13333333 0.11372549 0.11764706]
  [0.13333333 0.11372549 0.11764706]]

 [[0.14901961 0.19215686 0.34117647]
  [0.14509804 0.18823529 0.3372549 ]
  [0.14117647 0.18431373 0.33333333]
  ...
  [0.1372549  0.11764706 0.12156863]
  [0.13333333 0.11372549 0.11764706]
  [0.13333333 0.11372549 0.11764706]]

 [[0.15294118 0.19607843 0.34509804]
  [0.14901961 0.19215686 0.34117647]
  [0.14509804 0.18823529 0.3372549 ]
  ...
  [0.1372549  0.11764706 0.12156863]
  [0.1372549  0.11764706 0.12156863]
  [0.13333333 0.11372549 0.11764706]]

 ...

 [[0.13333333 0.16862745 0.31764706]
  [0.14117647 0.17647059 0.3254902 ]
  [0.1372549  0.17254902 0.32156863]
  ...
  [0.19215686 0.34117647 0.14509804]
  [0.19215686 0.34117647 0.14509804]
  [0.18823529 0.3372549  0.14117647]]

 [[0.13333333 0.16862745 0.31764706]
  [0.13333333 0.16862745 0.31764706]


## By mean (featurewise_center)



In [9]:
import tensorflow
import numpy as np
(x_train, y_train), (x_test, y_test) = tensorflow.keras.datasets.mnist.load_data()

In [10]:
# Calc the mean values of the dataset
mean_pixel = np.mean(x_train, axis=(0,1,2))

In [12]:
centralized_data = x_train - mean_pixel

In [14]:
centralized_data[0]

array([[-33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145],
       [-33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -33.31842145, -33.31842145],
       [-33.31842145, -33.31842145, -33.31842145, -33.31842145,
        -33.31842145, -33.31842145, -3

## Samplewise_center
Calc mean for each sample individualy

In [73]:
import tensorflow
import numpy as np
(x_train, y_train), (x_test, y_test) = tensorflow.keras.datasets.mnist.load_data()

In [74]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 170,
        253, 253, 253, 253, 253, 225, 172, 253, 242, 195,  64,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  49, 238, 253, 253, 253, 253,
        253, 253, 253, 253, 251,  93,  82,  82,  56,  39,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  18, 219, 253, 253, 253, 253,
        253, 198, 182, 247, 241,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  80, 156, 107, 253, 253,
        205,  11,   0,  43, 154,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   1, 154, 253,
         90,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253,
        190,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11, 190,
        253,  70,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  35,
        241, 225, 160, 108,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         81, 240, 253, 253, 119,  25,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  45, 186, 253, 253, 150,  27,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  16,  93, 252, 253, 187,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 249, 253, 249,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  46, 130, 183, 253, 253, 207,   2,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  39,
        148, 229, 253, 253, 253, 250, 182,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  24, 114, 221,
        253, 253, 253, 253, 201,  78,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  23,  66, 213, 253, 253,
        253, 253, 198,  81,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  18, 171, 219, 253, 253, 253, 253,
        195,  80,   9,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,  55, 172, 226, 253, 253, 253, 253, 244, 133,
         11,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0, 136, 253, 25

In [75]:
x_train[0].shape

(28, 28)

In [76]:
for i in range(len(x_train)):
  mean = np.mean(x_train[i], axis=(0, 1))
  x_train[i] = x_train[i] - mean

In [77]:
x_train[0]

array([[221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 224,
        239, 239, 239,  90, 100, 139, 247, 130, 219, 211,  91, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 251,   0,  58, 118, 134,
        217, 217, 217, 217, 217, 189, 136, 217, 206, 159,  28, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221,  13, 202, 217, 217, 217, 217,
        217, 217, 217, 217, 215,  57,  46,  46,  20,   3, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 239, 183, 217, 217, 217, 217,
        217, 162, 146, 211, 205, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221,  44, 120,  71, 217, 217,
        169, 232, 221,   7, 118, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 235, 222, 118, 217,
         54, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 103, 217,
        154, 223, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 232, 154,
        217,  34, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,   0,
        205, 189, 124,  72, 222, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
         45, 204, 217, 217,  83, 246, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221,   9, 150, 217, 217, 114, 248, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 237,  57, 216, 217, 151, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221, 221, 221, 213, 217, 213,  28, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221,  10,  94, 147, 217, 217, 171, 223, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,   3,
        112, 193, 217, 217, 217, 214, 146, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 245,  78, 185,
        217, 217, 217, 217, 165,  42, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 221, 221, 244,  30, 177, 217, 217,
        217, 217, 162,  45, 223, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 221, 221, 239, 135, 183, 217, 217, 217, 217,
        159,  44, 230, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221,  19, 136, 190, 217, 217, 217, 217, 208,  97,
        232, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221, 221,
        221, 221],
       [221, 221, 221, 221, 100, 217, 21

# featurewise_std_normalization

Normalization by std: divide the inputs by std of the dataset

In [83]:
import tensorflow
import numpy as np
(x_train, y_train), (x_test, y_test) = tensorflow.keras.datasets.mnist.load_data()

In [84]:
std = np.std(x_train, axis= (0,1))
x_train = (x_train)/std

In [85]:
x_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

# samplewise_std_normalization

In [86]:
import tensorflow
import numpy as np
(x_train, y_train), (x_test, y_test) = tensorflow.keras.datasets.mnist.load_data()

In [87]:
for i in range(len(x_train)):
  std = np.std(x_train[i], axis= (0,1))
  x_train[i] = x_train[i]/std

In [88]:
x_train[i]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 3, 3, 3, 3, 3, 3, 0,
        0, 0, 2, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 3, 1, 0, 0, 0, 0, 1, 3, 1,
        0, 3, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 1, 0, 0, 0, 0, 0, 0, 2, 3,
        3, 3, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 0, 0, 0, 1, 3, 3,
        2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 1, 2, 3, 3, 1,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 3, 3, 1, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 3, 3, 2, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 2, 3, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 3, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 3, 2, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 3, 2, 0, 0, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 3, 2, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]], dtype=uint8)

# CLAHE
(Contrast Limited Adaptive Histogram Equalization)

In [101]:
img = cv2.imread('/content/example-image.jpg', cv2.IMREAD_GRAYSCALE)

In [110]:
clahe = cv2.createCLAHE(clipLimit=80.0, tileGridSize=(8, 8))

In [111]:
clahe_image = clahe.apply(img)

In [112]:
from google.colab.patches import cv2_imshow
cv2_imshow(clahe_image)

Output hidden; open in https://colab.research.google.com to view.

## Brightness

In [114]:
image = cv2.imread('/content/example-image.jpg')
alpha = 1.5 # > 1 more bright and < 1 less bright
beta = 0 # Const value that is added after multiply pixels for aplha
brightened_image = cv2.addWeighted(image, alpha, np.zeros_like(image), 0, beta)
from google.colab.patches import cv2_imshow
cv2_imshow(brightened_image)

Output hidden; open in https://colab.research.google.com to view.

# Histogram Equalization

In [115]:
image = cv2.imread('/content/example-image.jpg')
image_yuv = cv2.cvtColor(image, cv2.COLOR_BGR2YUV)
# Equalize channel Y (luminance)
image_yuv[:,:,0] = cv2.equalizeHist(image_yuv[:,:,0])

# back to  BGR
equalized_image = cv2.cvtColor(image_yuv, cv2.COLOR_YUV2BGR)

from google.colab.patches import cv2_imshow
cv2_imshow(equalized_image)

Output hidden; open in https://colab.research.google.com to view.

## Blur

In [120]:
image = cv2.imread('/content/example-image.jpg')

In [124]:
gaussian_blur = cv2.GaussianBlur(image, (5, 5), 0)
from google.colab.patches import cv2_imshow
cv2_imshow(gaussian_blur)

Output hidden; open in https://colab.research.google.com to view.

In [126]:
median_blur = cv2.medianBlur(image, 5)
from google.colab.patches import cv2_imshow
cv2_imshow(median_blur)

Output hidden; open in https://colab.research.google.com to view.

In [127]:
bilateral_blur = cv2.bilateralFilter(image, 9, 75, 75)
from google.colab.patches import cv2_imshow
cv2_imshow(bilateral_blur)

Output hidden; open in https://colab.research.google.com to view.

# Bluring with filters

In [128]:
import numpy as np
kernel = np.ones((5,5),np.float32)/25
dst = cv2.filter2D(img,-1,kernel)
from google.colab.patches import cv2_imshow
cv2_imshow(dst)

Output hidden; open in https://colab.research.google.com to view.